@GameStoreAPI_HostAddress = https://localhost:7205

GET {{GameStoreAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{GameStoreAPI_HostAddress}}/api/account/register
Content-Type: application/json

{
  "username": "testt",
  "email": "trongamerytb@gmail.com",
  "password": "SenhaForte123!",
  "ConfirmPassword": "SenhaForte123!"
}

###

POST {{GameStoreAPI_HostAddress}}/api/account/register
Content-Type: application/json

{
  //RegisterAccountRequestDto
}

###

# Cenário 1: Buscar jogos populares (visão resumida)
GET {{GameStoreAPI_HostAddress}}/api/games?sort=popular&page=1&pageSize=5&view=summary
Accept: application/json

###

# Cenário 2: Buscar por um jogo específico (visão resumida)
GET {{GameStoreAPI_HostAddress}}/api/games?search=witcher
Accept: application/json

###

# Cenário 3: Buscar jogos populares (visão detalhada)
GET {{GameStoreAPI_HostAddress}}/api/games?sort=popular&pageSize=3&view=detailed
Accept: application/json
