@GameStoreAPI_HostAddress = https://localhost:7205

GET {{GameStoreAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{GameStoreAPI_HostAddress}}/api/account/register
Content-Type: application/json

{
  "username": "test",
  "email": "mrmundi12@gmail.com",
  "password": "SenhaForte123!",
  "ConfirmPassword": "SenhaForte123!"
}

###
